APTITUDE_QUESTIONS = [
    ("If a train travels 60 km in 1.5 hours, what is its average speed?", "30 km/h", "40 km/h", "45 km/h", "50 km/h", "B",
     "Average speed = distance / time = 60 / 1.5 = 40 km/h.", "Beginner"),
    ("What is 15% of 200?", "20", "25", "30", "35", "C",
     "15% of 200 = 0.15 × 200 = 30.", "Beginner"),
    ("A mobile phone is priced at ₹20,000. If a 10% discount is offered, what is the selling price?", "₹18,000", "₹18,500", "₹19,000", "₹19,500", "A",
 "10% of ₹20,000 = ₹2,000. Selling price = ₹20,000 − ₹2,000 = ₹18,000.", "Beginner"),
    ("Find the next number in the series: 2, 6, 12, 20, 30, ?", "36", "40", "42", "44", "C",
     "The differences are 4, 6, 8, 10, 12 -- so the next term is 30 + 12 = 42.", "Intermediate"),
    ("A is twice as old as B. Five years ago, A was three times as old as B. How old is B now?", "5", "10", "15", "20", "B",
     "Let B = x, A = 2x. Five years ago: 2x-5 = 3(x-5) → 2x-5 = 3x-15 → x = 10.", "Intermediate"),
    ("If all Bloops are Razzies and all Razzies are Lazzies, are all Bloops definitely Lazzies?", "Yes", "No", "Cannot be determined", "Only sometimes", "A",
     "This follows from transitive logic: if Bloops ⊆ Razzies and Razzies ⊆ Lazzies, then Bloops ⊆ Lazzies.", "Intermediate"),
    ("What comes next in the pattern: A, C, F, J, O, ?", "S", "T", "U", "V", "C",
     "The gaps increase by 1 each time (+2, +3, +4, +5, +6): A(1)+2=C(3), C+3=F(6), F+4=J(10), J+5=O(15), O+6=U(21).", "Advanced"),
    ("A car covers a distance at 60 km/h and returns the same distance at 40 km/h. What is the average speed for the whole trip?", "48 km/h", "50 km/h", "52 km/h", "55 km/h", "A",
     "Average speed for equal distances = (2 × 60 × 40) / (60 + 40) = 4800 / 100 = 48 km/h.", "Advanced"),
    ("If 5 workers can complete a task in 12 days, how many days will 10 workers take to complete the same task?", "3 days", "6 days", "8 days", "10 days", "B",
     "Work is constant: 5 × 12 = 60 worker-days. With 10 workers: 60 / 10 = 6 days.", "Intermediate"),
    ("Which number is the odd one out: 3, 5, 7, 9, 11, 15?", "3", "9", "11", "15", "B",
     "All the other numbers are prime except 9, which is 3 × 3 (composite).", "Beginner"),
    ("In a certain code, 'LISTEN' is written as 'MJTUFO'. How is 'SILENT' written in that code?", "TJMFOU", "TJMFOT", "SJMFOU", "TJNFOU", "A",
     "Each letter is shifted forward by 1 in the alphabet (L→M, I→J, S→T...), so SILENT becomes TJMFOU.", "Advanced"),
    ("A sum of money doubles itself in 8 years at simple interest. What is the rate of interest per annum?", "10%", "12.5%", "15%", "20%", "B",
     "If principal doubles, SI = P over 8 years, so Rate = (100 × P) / (P × 8) = 12.5% per annum.", "Advanced"),
    ("If today is Wednesday, what day will it be after 100 days?", "Monday", "Tuesday", "Thursday", "Friday", "D",
     "100 mod 7 = 2, so add 2 days to Wednesday: Thursday, then Friday.", "Intermediate"),
    ("Find the missing number: 4, 9, 16, 25, ?, 49", "30", "36", "40", "42", "B",
     "The series consists of perfect squares: 2², 3², 4², 5², 6²=36, 7².", "Beginner"),
    ("Pointing to a photograph, a man says, \"She is the daughter of my grandfather's only son.\" How is the woman related to the man?", "Mother", "Sister", "Aunt", "Cousin", "B",
     "The man's grandfather's only son is the man's father, so the daughter of the man's father is his sister.", "Advanced"),
]
