CN_QUESTIONS = [
    ("What does IP stand for in networking?", "Internal Protocol", "Internet Protocol", "Integrated Path", "Instant Ping", "B",
     "IP (Internet Protocol) is the principal set of rules for routing and addressing packets across networks.", "Beginner"),
    ("How many layers does the OSI model have?", "5", "6", "7", "8", "C",
     "The OSI (Open Systems Interconnection) model consists of 7 layers, from Physical to Application.", "Beginner"),
    ("Which layer of the OSI model is responsible for routing?", "Data Link", "Network", "Transport", "Session", "B",
     "The Network layer (Layer 3) handles logical addressing and routing of packets between networks.", "Beginner"),
    ("What is the primary purpose of DNS?", "Encrypting network traffic", "Translating human-readable domain names into IP addresses", "Compressing data packets", "Managing firewall rules", "B",
     "DNS (Domain Name System) resolves domain names like example.com into their corresponding IP addresses.", "Beginner"),
    ("What does TCP stand for?", "Transfer Control Protocol", "Transmission Control Protocol", "Total Connection Protocol", "Text Copy Protocol", "B",
     "TCP (Transmission Control Protocol) provides reliable, ordered, and error-checked delivery of data.", "Beginner"),
    ("What is the key difference between TCP and UDP?", "UDP is connection-oriented; TCP is not", "TCP guarantees reliable, ordered delivery; UDP does not", "They are identical protocols", "UDP is always slower than TCP", "B",
     "TCP establishes a connection and guarantees reliable, ordered delivery, while UDP is connectionless and faster but unreliable.", "Intermediate"),
    ("What is the default port number for HTTP?", "21", "22", "80", "443", "C",
     "HTTP traffic conventionally uses port 80, while HTTPS uses port 443.", "Beginner"),
    ("What is the default port number for HTTPS?", "80", "8080", "443", "21", "C",
     "HTTPS (HTTP Secure) conventionally uses port 443.", "Beginner"),
    ("What does a subnet mask do?", "Encrypts IP addresses", "Divides an IP address into network and host portions", "Assigns MAC addresses", "Blocks malicious traffic", "B",
     "A subnet mask determines which portion of an IP address refers to the network and which refers to the host.", "Intermediate"),
    ("What is the purpose of ARP (Address Resolution Protocol)?", "Resolving domain names to IPs", "Mapping an IP address to its corresponding MAC address on a local network", "Encrypting network packets", "Routing packets between networks", "B",
     "ARP resolves a known IP address to its corresponding physical MAC address within a local network segment.", "Intermediate"),
    ("What is a firewall primarily used for?", "Speeding up internet connections", "Monitoring and controlling incoming/outgoing network traffic based on security rules", "Compressing files for transfer", "Assigning IP addresses automatically", "B",
     "A firewall enforces security policies by filtering network traffic based on predefined rules.", "Intermediate"),
    ("What does DHCP do?", "Encrypts network traffic", "Automatically assigns IP addresses to devices on a network", "Resolves domain names", "Manages firewall rules", "B",
     "DHCP (Dynamic Host Configuration Protocol) automatically assigns IP addresses and network configuration to devices.", "Intermediate"),
    ("What is the purpose of a three-way handshake in TCP?", "To encrypt the connection", "To establish a reliable connection between client and server before data transfer", "To compress data packets", "To terminate a connection", "B",
     "The TCP three-way handshake (SYN, SYN-ACK, ACK) establishes a reliable connection between two hosts before data exchange begins.", "Advanced"),
    ("What is NAT (Network Address Translation) used for?", "Encrypting DNS queries", "Allowing multiple devices on a private network to share a single public IP address", "Assigning MAC addresses", "Load balancing servers", "B",
     "NAT translates private IP addresses to a shared public IP address, conserving public address space and adding a layer of privacy.", "Advanced"),
    ("What is the main difference between a router and a switch?", "There is no difference", "A router connects different networks and routes packets based on IP; a switch connects devices within the same network using MAC addresses", "Switches operate at the Network layer; routers operate at the Physical layer", "Routers cannot connect to the internet", "B",
     "Routers forward packets between different networks based on IP addresses, while switches connect devices within a single local network using MAC addresses.", "Advanced"),
    ("What does the term \"latency\" refer to in networking?", "The maximum bandwidth of a connection", "The time delay for data to travel from source to destination", "The number of connected devices", "The encryption strength of a connection", "B",
     "Latency measures the time delay between sending and receiving data across a network.", "Beginner"),
]
