CPP_QUESTIONS = [
    ("Which header file is required for standard input/output in C?", "<iostream>", "<stdio.h>", "<stdlib.h>", "<conio.h>", "B",
     "`<stdio.h>` provides standard input/output functions like `printf()` and `scanf()` in C.", "Beginner"),
    ("Which header is used for input/output in C++?", "<stdio.h>", "<iostream>", "<fstream>", "<cstdlib>", "B",
     "`<iostream>` provides input/output stream objects like `cin` and `cout` in C++.", "Beginner"),
    ("What is the correct way to declare a pointer in C?", "int ptr;", "int *ptr;", "pointer int ptr;", "int &ptr;", "B",
     "A pointer is declared using an asterisk before the variable name, e.g. `int *ptr;`.", "Beginner"),
    ("Which operator is used to access the value at a pointer's address in C?", "&", "*", "->", "%", "B",
     "The dereference operator `*` accesses the value stored at the address a pointer points to.", "Beginner"),
    ("What does the `&` operator do when applied to a variable in C?", "Dereferences it", "Returns its memory address", "Multiplies it", "Compares it", "B",
     "The `&` operator returns the memory address of a variable.", "Beginner"),
    ("What is the correct function signature for `main` in C?", "void main(void)", "int main(void)", "main() int", "function main()", "B",
     "The standard, portable signature is `int main(void)`, returning an integer exit status.", "Beginner"),
    ("What does `malloc()` do in C?", "Frees allocated memory", "Dynamically allocates a block of memory on the heap", "Declares a static variable", "Compares two memory blocks", "B",
     "`malloc()` dynamically allocates a specified number of bytes on the heap and returns a pointer to it.", "Intermediate"),
    ("Which keyword is used in C++ to define a class?", "struct", "object", "class", "type", "C",
     "The `class` keyword defines a new class in C++.", "Beginner"),
    ("What is the default access specifier for members of a C++ class?", "public", "private", "protected", "internal", "B",
     "Class members in C++ are `private` by default (as opposed to `struct`, where they default to `public`).", "Intermediate"),
    ("What is function overloading in C++?", "Defining a function with a body inside another function", "Defining multiple functions with the same name but different parameter lists", "Calling a function recursively", "Declaring a function as static", "B",
     "Overloading lets multiple functions share the same name as long as their parameter lists differ.", "Intermediate"),
    ("What does the `new` keyword do in C++?", "Declares a variable", "Dynamically allocates memory on the heap and returns a pointer", "Frees memory", "Creates a namespace", "B",
     "`new` allocates memory dynamically on the heap for an object and returns a pointer to it; paired with `delete` to free it.", "Intermediate"),
    ("What is a destructor in C++?", "A function that allocates memory", "A special member function called automatically when an object is destroyed", "A constructor overload", "A type of pointer", "B",
     "A destructor (`~ClassName()`) is automatically invoked when an object goes out of scope or is explicitly deleted, to clean up resources.", "Intermediate"),
    ("What is the purpose of the `const` keyword in C/C++?", "To declare a loop", "To indicate that a variable's value cannot be changed after initialization", "To allocate memory dynamically", "To define a macro", "B",
     "`const` marks a variable as read-only after its initial assignment, helping prevent accidental modification.", "Beginner"),
    ("What is a memory leak in C/C++?", "Allocating too little memory", "Failing to free dynamically allocated memory that is no longer needed", "A compiler warning only", "Using too many variables", "B",
     "A memory leak occurs when dynamically allocated memory is never freed, gradually consuming available memory.", "Advanced"),
    ("What does the C++ `virtual` keyword enable?", "Faster compilation", "Runtime polymorphism through dynamic method dispatch", "Static memory allocation", "Header file inclusion", "B",
     "`virtual` functions enable runtime polymorphism, allowing derived class overrides to be called through a base class pointer/reference.", "Advanced"),
    ("What is the difference between `struct` and `class` in C++?", "There is no difference at all", "Members of `struct` default to public; members of `class` default to private", "`struct` cannot have methods", "`class` cannot be inherited", "B",
     "The only functional difference is the default access specifier: `public` for `struct`, `private` for `class`.", "Intermediate"),
]
