DS_QUESTIONS = [
    ("Which data structure uses LIFO (Last In, First Out) order?", "Queue", "Stack", "Array", "Linked List", "B",
     "A stack follows the LIFO principle: the last element pushed is the first one popped.", "Beginner"),
    ("Which data structure uses FIFO (First In, First Out) order?", "Stack", "Queue", "Tree", "Graph", "B",
     "A queue follows FIFO: the first element added is the first one removed.", "Beginner"),
    ("What is the time complexity of accessing an element by index in an array?", "O(n)", "O(log n)", "O(1)", "O(n^2)", "C",
     "Arrays offer constant-time O(1) access to any element via its index, due to contiguous memory storage.", "Beginner"),
    ("What is the main advantage of a linked list over an array?", "Faster indexed access", "Efficient insertion and deletion without shifting elements", "Uses less memory always", "Better cache performance", "B",
     "Linked lists allow O(1) insertion/deletion at a known position without shifting other elements, unlike arrays.", "Beginner"),
    ("What is a binary search tree (BST)?", "A tree where every node has exactly two children", "A tree where the left subtree contains smaller values and the right subtree contains larger values", "A tree with no root", "A type of linked list", "B",
     "In a BST, for every node, values in the left subtree are smaller and values in the right subtree are larger than the node.", "Intermediate"),
    ("What is the average time complexity of searching in a balanced binary search tree?", "O(1)", "O(log n)", "O(n)", "O(n log n)", "B",
     "A balanced BST allows search operations to complete in O(log n) time by halving the search space at each step.", "Intermediate"),
    ("Which data structure is typically used to implement recursion internally?", "Queue", "Stack", "Heap (data structure)", "Array", "B",
     "Function calls (including recursive ones) are managed using a call stack that stores each call's execution context.", "Beginner"),
    ("What is a hash table primarily used for?", "Sorting elements", "Storing key-value pairs with average O(1) lookup, insertion, and deletion", "Representing hierarchical data", "Finding shortest paths", "B",
     "A hash table maps keys to values using a hash function, offering average constant-time operations.", "Intermediate"),
    ("What is a collision in a hash table?", "A syntax error", "When two different keys hash to the same index", "When the table runs out of memory", "When keys are sorted incorrectly", "B",
     "A collision occurs when two distinct keys produce the same hash index, requiring a resolution strategy like chaining.", "Intermediate"),
    ("What is the time complexity of the best-case scenario for bubble sort?", "O(n)", "O(n log n)", "O(n^2)", "O(1)", "A",
     "Bubble sort runs in O(n) time in the best case, when the array is already sorted (with an early-exit optimization).", "Intermediate"),
    ("What is the average time complexity of quicksort?", "O(n)", "O(n log n)", "O(n^2)", "O(log n)", "B",
     "Quicksort has an average time complexity of O(n log n), though its worst case is O(n^2).", "Intermediate"),
    ("What is a graph in data structures?", "A linear sequence of elements", "A collection of nodes (vertices) connected by edges", "A type of sorted array", "A fixed-size table", "B",
     "A graph consists of vertices (nodes) connected by edges, used to represent relationships like networks or maps.", "Intermediate"),
    ("What is the difference between a stack and a heap (memory) in terms of allocation?", "There is no difference", "Stack memory is managed automatically with LIFO order; heap memory is manually/dynamically allocated", "Heap is always faster than stack", "Stack memory has no size limit", "B",
     "Stack memory is automatically managed in LIFO order for function calls, while heap memory is dynamically allocated and must be managed explicitly (or via garbage collection).", "Advanced"),
    ("What is the purpose of a min-heap data structure?", "To store data in sorted array order", "To efficiently retrieve the minimum element in O(1) with O(log n) insertion/removal", "To perform string matching", "To represent graphs only", "B",
     "A min-heap keeps the smallest element at the root, enabling O(1) access to the minimum and O(log n) insert/remove operations.", "Advanced"),
    ("What is dynamic programming primarily used to optimize?", "Memory allocation only", "Problems with overlapping subproblems and optimal substructure, by storing intermediate results", "Network routing exclusively", "Sorting algorithms only", "B",
     "Dynamic programming solves complex problems by breaking them into overlapping subproblems and caching (memoizing) their results.", "Advanced"),
    ("What is the worst-case time complexity of searching in an unbalanced binary search tree?", "O(1)", "O(log n)", "O(n)", "O(n^2)", "C",
     "In the worst case (a completely skewed tree resembling a linked list), search degrades to O(n).", "Advanced"),
]
