DBMS_QUESTIONS = [
    ("What does DBMS stand for?", "Database Management System", "Data Backup Management Software", "Digital Base Management Service", "Database Model Storage", "A",
     "DBMS stands for Database Management System, software that manages databases and their access.", "Beginner"),
    ("What is a primary key?", "A key that can have duplicate values", "A column (or set of columns) that uniquely identifies each row in a table", "An encrypted password field", "A foreign table reference", "B",
     "A primary key uniquely identifies each record in a table and cannot contain duplicate or NULL values.", "Beginner"),
    ("What is the main purpose of normalization in a DBMS?", "Increase data redundancy", "Reduce data redundancy and improve data integrity", "Speed up hardware", "Encrypt tables", "B",
     "Normalization organizes data to reduce redundancy and dependency issues within the database.", "Beginner"),
    ("What is a foreign key used for?", "To uniquely identify rows in its own table", "To create a link between two tables by referencing another table's primary key", "To store encrypted data", "To sort table data", "B",
     "A foreign key establishes a relationship between two tables by referencing the primary key of another table.", "Beginner"),
    ("What does the term \"entity\" refer to in an Entity-Relationship (ER) diagram?", "A database query", "A real-world object or concept represented as a table", "A type of index", "A stored procedure", "B",
     "In ER modeling, an entity represents a distinguishable real-world object, typically mapped to a table.", "Beginner"),
    ("What is a composite key?", "A key made up of a single unique column", "A primary key composed of two or more columns together", "An encrypted key", "A key used only for indexing", "B",
     "A composite key uses a combination of two or more columns to uniquely identify a row.", "Intermediate"),
    ("Which normal form eliminates partial dependency on a composite primary key?", "1NF", "2NF", "3NF", "BCNF", "B",
     "Second Normal Form (2NF) requires that every non-key attribute be fully dependent on the entire primary key, not just part of it.", "Intermediate"),
    ("What is the difference between a DBMS and an RDBMS?", "There is no difference", "RDBMS organizes data into related tables enforcing relational constraints; DBMS may not", "DBMS is always faster", "RDBMS cannot use SQL", "B",
     "An RDBMS (Relational DBMS) organizes data into structured tables with enforced relationships, unlike a generic DBMS.", "Intermediate"),
    ("What is a deadlock in a DBMS?", "A backup failure", "A situation where two or more transactions wait indefinitely for each other's locks", "A syntax error in a query", "A type of index corruption", "B",
     "A deadlock occurs when transactions hold locks the others need, causing them to wait on each other forever.", "Intermediate"),
    ("What does the term \"referential integrity\" ensure?", "Passwords are encrypted", "Foreign key values always correspond to existing primary key values", "Tables are always normalized", "Queries execute faster", "B",
     "Referential integrity ensures that a foreign key value always matches an existing primary key in the referenced table.", "Intermediate"),
    ("What is a view in a DBMS?", "A physical copy of a table", "A virtual table based on the result of a stored query", "A type of index", "A backup mechanism", "B",
     "A view is a virtual table representing the result of a stored SQL query, without physically duplicating the data.", "Intermediate"),
    ("What is the purpose of a transaction log in a DBMS?", "To store user passwords", "To record all changes for recovery and rollback purposes", "To index tables faster", "To store views", "B",
     "The transaction log records changes made to the database, enabling recovery and rollback in case of failure.", "Advanced"),
    ("What does the CAP theorem state about distributed databases?", "A system can guarantee Consistency, Availability, and Partition tolerance simultaneously", "A distributed system can only guarantee at most two of Consistency, Availability, and Partition tolerance at once", "CAP applies only to relational databases", "CAP is unrelated to distributed systems", "B",
     "The CAP theorem states that a distributed data store can provide only two of the three guarantees: Consistency, Availability, Partition tolerance.", "Advanced"),
    ("What is denormalization?", "The process of removing all keys from a table", "Intentionally introducing redundancy to improve read performance", "A type of encryption", "Converting a table into a view", "B",
     "Denormalization deliberately adds redundant data to reduce the need for costly joins, trading storage for read speed.", "Advanced"),
    ("What is the difference between a clustered and non-clustered index?", "There is no difference", "A clustered index determines the physical order of data; a non-clustered index is a separate structure", "Non-clustered indexes are always faster", "Clustered indexes cannot be used on primary keys", "B",
     "A clustered index sorts and stores the data rows of the table based on the key, while a non-clustered index is a separate lookup structure.", "Advanced"),
    ("What isolation level prevents dirty reads but may still allow non-repeatable reads?", "Read Uncommitted", "Read Committed", "Serializable", "None of the above", "B",
     "Read Committed prevents transactions from reading uncommitted (dirty) data, but non-repeatable reads can still occur.", "Advanced"),
]
