HTML_CSS_QUESTIONS = [
    ("What does HTML stand for?", "Hyperlinks and Text Markup Language", "HyperText Markup Language", "Home Tool Markup Language", "HyperText Modern Language", "B",
     "HTML stands for HyperText Markup Language, the standard language for creating web pages.", "Beginner"),
    ("Which tag is used to create a hyperlink in HTML?", "<link>", "<a>", "<href>", "<nav>", "B",
     "The `<a>` (anchor) tag with an `href` attribute creates a hyperlink.", "Beginner"),
    ("Which HTML tag is used to define an unordered list?", "<ol>", "<list>", "<ul>", "<li>", "C",
     "`<ul>` defines an unordered (bulleted) list, with `<li>` for each list item.", "Beginner"),
    ("What is the correct HTML element for the largest heading?", "<heading>", "<h6>", "<h1>", "<head>", "C",
     "`<h1>` represents the largest and most important heading; `<h6>` is the smallest.", "Beginner"),
    ("Which CSS property changes the text color of an element?", "font-color", "text-color", "color", "background-color", "C",
     "The `color` property sets the color of an element's text content.", "Beginner"),
    ("How do you select an element with id \"header\" in CSS?", ".header", "#header", "*header", "header{}", "B",
     "The `#` symbol targets an element by its `id` attribute in CSS.", "Beginner"),
    ("Which property is used to change the background color in CSS?", "color", "bgcolor", "background-color", "background-fill", "C",
     "`background-color` sets the background color of an element.", "Beginner"),
    ("What does the CSS `box-sizing: border-box` property do?", "Removes the border", "Includes padding and border within the element's total width/height", "Adds a shadow", "Hides the box", "B",
     "`border-box` makes the width/height include padding and border, simplifying layout calculations.", "Intermediate"),
    ("Which HTML attribute specifies an alternate text for an image?", "title", "alt", "src", "longdesc", "B",
     "The `alt` attribute provides alternate text for an image, important for accessibility and when the image fails to load.", "Beginner"),
    ("What is the default value of the CSS `position` property?", "relative", "fixed", "absolute", "static", "D",
     "Elements are positioned `static` by default, following normal document flow.", "Intermediate"),
    ("Which CSS layout model is designed for one-dimensional layouts (row or column)?", "Grid", "Flexbox", "Float", "Table", "B",
     "Flexbox is designed for laying out items in a single dimension, either as a row or a column.", "Intermediate"),
    ("Which CSS layout model is best suited for two-dimensional layouts?", "Flexbox", "Float", "CSS Grid", "Inline-block", "C",
     "CSS Grid handles both rows and columns simultaneously, making it ideal for complex two-dimensional layouts.", "Intermediate"),
    ("What does the `z-index` CSS property control?", "Horizontal position", "Element opacity", "Stacking order along the z-axis", "Font size scaling", "C",
     "`z-index` determines which positioned elements appear in front of or behind others when they overlap.", "Intermediate"),
    ("Which HTML5 tag is used to embed video content?", "<media>", "<video>", "<embed>", "<film>", "B",
     "The `<video>` tag natively embeds video content in HTML5.", "Beginner"),
    ("What does `em` represent as a CSS unit?", "A fixed pixel size", "A unit relative to the font-size of the element", "A percentage of the viewport", "An absolute unit like inches", "B",
     "`em` is relative to the font-size of the element (or its parent), making it useful for scalable typography.", "Intermediate"),
    ("Which CSS pseudo-class targets an element when the mouse is over it?", ":focus", ":hover", ":active", ":visited", "B",
     "`:hover` applies styles while the user's pointer is over the element.", "Beginner"),
    ("What is the purpose of a CSS media query?", "To embed audio files", "To apply styles conditionally based on device characteristics like screen width", "To load external fonts", "To validate HTML", "B",
     "Media queries let you apply different CSS rules depending on conditions like viewport width, enabling responsive design.", "Intermediate"),
    ("Which HTML element is used to define the metadata of a document?", "<meta>", "<head>", "<body>", "<info>", "B",
     "The `<head>` element contains metadata (title, links, meta tags, etc.) about the HTML document.", "Beginner"),
    ("What does `flex-direction: column` do in a flex container?", "Aligns items diagonally", "Stacks flex items vertically instead of horizontally", "Removes all spacing", "Reverses text direction", "B",
     "`flex-direction: column` arranges flex items in a vertical stack rather than the default horizontal row.", "Advanced"),
    ("Which CSS technique is commonly used to make text responsive across screen sizes?", "Fixed pixel units only", "clamp() or relative units like rem/vw", "Uppercase text", "Inline styles only", "B",
     "Functions like `clamp()` combined with relative units (`rem`, `vw`) allow font sizes to scale fluidly with the viewport.", "Advanced"),
    ("What is the CSS specificity order (lowest to highest) among these selectors?", "ID > class > element", "class > ID > element", "element < class < ID", "ID < element < class", "C",
     "CSS specificity increases from type/element selectors, to class/attribute selectors, to ID selectors.", "Advanced"),
]
