JAVASCRIPT_QUESTIONS = [
    ("Which keyword declares a block-scoped variable in JavaScript?", "var", "let", "define", "int", "B",
     "`let` (along with `const`) declares a block-scoped variable, unlike `var` which is function-scoped.", "Beginner"),
    ("What does `typeof \"hello\"` return?", "string", "text", "str", "char", "A",
     "`typeof` on a string literal returns the string `\"string\"`.", "Beginner"),
    ("Which symbol is used for strict equality comparison in JavaScript?", "=", "==", "===", "!=", "C",
     "`===` checks both value and type equality without type coercion, unlike `==`.", "Beginner"),
    ("How do you write a comment in JavaScript?", "<!-- comment -->", "# comment", "// comment", "' comment", "C",
     "JavaScript uses `//` for single-line comments and `/* */` for multi-line comments.", "Beginner"),
    ("What is the correct way to create a function in JavaScript?", "function myFunc() {}", "func myFunc() {}", "def myFunc() {}", "create myFunc() {}", "A",
     "Functions are declared using the `function` keyword followed by a name and parentheses.", "Beginner"),
    ("Which method converts a JSON string into a JavaScript object?", "JSON.stringify()", "JSON.parse()", "JSON.convert()", "JSON.toObject()", "B",
     "`JSON.parse()` converts a JSON-formatted string into a JavaScript object.", "Beginner"),
    ("What will `console.log(typeof null)` output?", "null", "undefined", "object", "boolean", "C",
     "Due to a long-standing JavaScript quirk, `typeof null` returns `\"object\"`.", "Beginner"),
    ("Which array method adds an element to the end of an array?", "push()", "pop()", "shift()", "unshift()", "A",
     "`push()` adds one or more elements to the end of an array and returns the new length.", "Beginner"),
    ("What does `NaN` stand for in JavaScript?", "Not a Node", "Not a Number", "Null and None", "New Array Node", "B",
     "`NaN` represents a value that is \"Not a Number\", often the result of an invalid math operation.", "Beginner"),
    ("Which of the following creates an empty array?", "let arr = ();", "let arr = {};", "let arr = [];", "let arr = new Set();", "C",
     "Square brackets `[]` create an empty array literal in JavaScript.", "Beginner"),
    ("What is a closure in JavaScript?", "A function that has no parameters", "A function that remembers variables from its outer scope even after that scope has closed", "A way to close a browser tab", "A syntax error handler", "B",
     "A closure lets an inner function access variables from its enclosing scope even after the outer function returns.", "Intermediate"),
    ("What does the `map()` array method return?", "The original array modified in place", "A new array with the results of calling a function on every element", "A single value", "undefined", "B",
     "`map()` creates a new array populated with the results of calling the provided function on every element.", "Intermediate"),
    ("What is the purpose of `async`/`await` in JavaScript?", "To declare global variables", "To write asynchronous code that looks synchronous", "To define classes", "To style HTML elements", "B",
     "`async`/`await` provides syntax for writing promise-based asynchronous code in a more readable, synchronous style.", "Intermediate"),
    ("What does `this` refer to inside a regular (non-arrow) object method?", "The global object always", "The object the method was called on", "The function itself", "undefined always", "B",
     "Inside a regular method, `this` refers to the object that invoked the method.", "Intermediate"),
    ("Which of these correctly checks if a variable is an array?", "typeof arr === 'array'", "Array.isArray(arr)", "arr instanceof Object", "arr.isArray()", "B",
     "`Array.isArray()` is the reliable way to check if a value is an array, since `typeof` returns `\"object\"` for arrays.", "Intermediate"),
    ("What is event bubbling in the DOM?", "Events triggering only on the exact clicked element", "Events propagating from the target element up through its ancestors", "A method to prevent default actions", "A way to bundle multiple events", "B",
     "Event bubbling means an event fires on the target element first, then propagates upward through its ancestor elements.", "Intermediate"),
    ("What does the spread operator (`...`) do with an array?", "Deletes elements", "Expands array elements into individual elements", "Converts array to string", "Sorts the array", "B",
     "The spread operator expands an iterable like an array into its individual elements, useful for copying or merging.", "Intermediate"),
    ("What is the output of `[1, 2, 3].length`?", "2", "3", "4", "undefined", "B",
     "The `length` property returns the number of elements in the array, which is `3`.", "Beginner"),
    ("What does `Promise.all()` do?", "Runs promises one after another", "Resolves when all provided promises resolve, or rejects if any reject", "Cancels all promises", "Only works with two promises", "B",
     "`Promise.all()` takes an iterable of promises and resolves once every promise resolves, or rejects immediately if one fails.", "Advanced"),
    ("What is the difference between `let` and `const`?", "There is no difference", "`const` variables cannot be reassigned after declaration", "`let` variables are hoisted differently", "`const` is function-scoped only", "B",
     "`const` declares a variable whose binding cannot be reassigned, though object properties within it can still change.", "Beginner"),
    ("What does the JavaScript event loop primarily manage?", "CSS rendering", "Execution order of synchronous code, microtasks, and macrotasks", "Memory garbage collection only", "HTML parsing", "B",
     "The event loop coordinates the call stack, microtask queue (e.g. promises), and macrotask queue (e.g. setTimeout) to handle asynchronous execution.", "Advanced"),
    ("What is prototypal inheritance in JavaScript?", "Objects inheriting properties/methods directly from other objects via the prototype chain", "A syntax error", "Class-based inheritance only", "A CSS feature", "A",
     "JavaScript objects can inherit features from other objects through the prototype chain, rather than strictly through classes.", "Advanced"),
    ("What does `Array.prototype.reduce()` do?", "Filters array elements", "Reduces the array to a single accumulated value using a callback", "Sorts the array in place", "Reverses the array", "B",
     "`reduce()` executes a reducer callback on each element, accumulating a single output value (e.g. a sum).", "Advanced"),
]
