JAVA_QUESTIONS = [
    ("Which company originally developed Java?", "Microsoft", "Sun Microsystems", "Apple", "IBM", "B",
     "Java was originally developed by Sun Microsystems, released in 1995 (Sun was later acquired by Oracle).", "Beginner"),
    ("What is the correct extension for a Java source file?", ".jav", ".java", ".jv", ".class", "B",
     "Java source files use the `.java` extension; compiled bytecode uses `.class`.", "Beginner"),
    ("Which of these is a primitive data type in Java?", "String", "Integer", "int", "ArrayList", "C",
     "`int` is a primitive type; `String`, `Integer`, and `ArrayList` are all reference (object) types.", "Beginner"),
    ("What is the entry point method for a Java application?", "start()", "main()", "run()", "init()", "B",
     "Java programs begin execution from `public static void main(String[] args)`.", "Beginner"),
    ("Which keyword is used to create an object in Java?", "new", "create", "object", "make", "A",
     "The `new` keyword allocates memory and creates an instance of a class.", "Beginner"),
    ("How do you write a single-line comment in Java?", "# comment", "<!-- comment -->", "// comment", "' comment", "C",
     "Java uses `//` for single-line comments, similar to C and JavaScript.", "Beginner"),
    ("What is the default value of a boolean variable in Java?", "true", "false", "0", "null", "B",
     "Uninitialized instance boolean fields default to `false` in Java.", "Beginner"),
    ("Which of the following is used to inherit a class in Java?", "implements", "extends", "inherits", "super", "B",
     "The `extends` keyword is used for class inheritance in Java.", "Beginner"),
    ("What does JVM stand for?", "Java Virtual Machine", "Java Verified Method", "Just Virtual Machine", "Java Variable Manager", "A",
     "JVM (Java Virtual Machine) executes Java bytecode, enabling platform independence.", "Beginner"),
    ("Which access modifier makes a member accessible only within its own class?", "public", "protected", "private", "default", "C",
     "`private` restricts access strictly to within the declaring class.", "Beginner"),
    ("What is the purpose of the `static` keyword in Java?", "To make a variable constant", "To associate a member with the class rather than instances", "To prevent inheritance", "To handle exceptions", "B",
     "`static` members belong to the class itself, shared across all instances, rather than to any one object.", "Intermediate"),
    ("What is method overloading in Java?", "Defining multiple methods with the same name but different parameters", "Overriding a parent class method", "Calling a method recursively", "Declaring a method as final", "A",
     "Overloading allows multiple methods in the same class to share a name but differ in parameter type or count.", "Intermediate"),
    ("Which collection class does not allow duplicate elements?", "ArrayList", "LinkedList", "HashSet", "Vector", "C",
     "`HashSet` is backed by a hash table and does not permit duplicate elements.", "Intermediate"),
    ("What is the purpose of the `finally` block in Java exception handling?", "It only runs if an exception occurs", "It always runs, regardless of whether an exception occurred", "It replaces the catch block", "It is optional and rarely used", "B",
     "Code in a `finally` block executes whether or not an exception was thrown, commonly used for cleanup.", "Intermediate"),
    ("What is an interface in Java primarily used for?", "Storing data fields only", "Defining a contract of methods that implementing classes must provide", "Creating a subclass automatically", "Compiling code faster", "B",
     "An interface defines method signatures that implementing classes must provide, enabling abstraction.", "Intermediate"),
    ("What does the `this` keyword refer to in Java?", "The parent class", "The current instance of the class", "A static method", "The superclass constructor", "B",
     "`this` refers to the current object instance within a non-static method or constructor.", "Intermediate"),
    ("Which of these correctly declares an array of integers in Java?", "int arr[] = new int[5];", "array int arr = new(5);", "int[5] arr;", "arr int[] = new int(5);", "A",
     "`int arr[] = new int[5];` (or equivalently `int[] arr = new int[5];`) is valid Java array syntax.", "Intermediate"),
    ("What is the difference between `==` and `.equals()` for objects in Java?", "They are identical", "`==` compares references; `.equals()` compares logical content", "`.equals()` compares references; `==` compares content", "Neither can compare objects", "B",
     "`==` checks whether two references point to the same object, while `.equals()` (when overridden) compares content.", "Advanced"),
    ("What is a checked exception in Java?", "An exception that must be declared or handled at compile time", "An exception ignored by the compiler", "An exception only thrown by JVM", "An exception that never needs handling", "A",
     "Checked exceptions (like `IOException`) must be either caught or declared in a method's `throws` clause.", "Advanced"),
    ("What is the purpose of the `synchronized` keyword in Java?", "To speed up execution", "To allow only one thread to access a block/method at a time", "To declare a constant", "To import packages", "B",
     "`synchronized` ensures mutual exclusion, allowing only one thread to execute a critical section at a time.", "Advanced"),
    ("What does garbage collection in Java do?", "Deletes source code comments", "Automatically reclaims memory used by unreachable objects", "Removes unused imports", "Compresses class files", "B",
     "Java's garbage collector automatically frees memory occupied by objects no longer referenced by the program.", "Advanced"),
    ("What is polymorphism in object-oriented Java programming?", "Having multiple classes with the same name", "The ability of an object to take many forms via overriding/overloading", "Restricting access to fields", "Compiling code in multiple passes", "B",
     "Polymorphism lets objects be treated as instances of their parent type while executing type-specific behavior.", "Intermediate"),
]
