OS_QUESTIONS = [
    ("What is the primary function of an operating system?", "To compile programs", "To manage hardware resources and provide services for computer programs", "To design websites", "To encrypt files only", "B",
     "An OS manages hardware resources (CPU, memory, I/O) and provides a platform for running application software.", "Beginner"),
    ("What is a process in an operating system?", "A static file on disk", "An instance of a program in execution", "A type of hardware device", "A network protocol", "B",
     "A process is a program in execution, including its code, data, and current activity state.", "Beginner"),
    ("What is the difference between a process and a thread?", "There is no difference", "A thread is a lightweight unit of execution within a process, sharing its memory space", "A process is smaller than a thread", "Threads cannot share memory", "B",
     "Threads exist within a process and share its memory/resources, making them lighter-weight than separate processes.", "Beginner"),
    ("What does CPU scheduling determine?", "Which files to delete", "Which process gets to use the CPU at a given time", "The screen resolution", "Network bandwidth allocation", "B",
     "CPU scheduling algorithms decide which of the ready processes gets CPU time next.", "Beginner"),
    ("What is virtual memory?", "Physical RAM only", "A memory management technique that gives the illusion of a large, contiguous address space using disk storage", "A type of cache", "A backup storage device", "B",
     "Virtual memory allows a system to use disk space to extend the effective size of RAM, giving processes more address space than physically available.", "Beginner"),
    ("What is a deadlock in the context of operating systems?", "A crashed application", "A state where processes are stuck waiting indefinitely for resources held by each other", "A type of memory leak", "A scheduling algorithm", "B",
     "A deadlock occurs when a set of processes are blocked, each waiting for a resource held by another process in the set.", "Intermediate"),
    ("Which of the following is a necessary condition for deadlock (Coffman conditions)?", "Preemption", "Mutual exclusion", "Unlimited resources", "Single-threading", "B",
     "Mutual exclusion (at least one resource must be non-shareable) is one of the four necessary conditions for deadlock.", "Intermediate"),
    ("What is the purpose of a page replacement algorithm?", "To format the disk", "To decide which memory page to evict when a new page must be loaded and memory is full", "To schedule CPU processes", "To manage network packets", "B",
     "Page replacement algorithms (like LRU or FIFO) choose which existing page to remove from memory to make room for a new one.", "Intermediate"),
    ("What does the term \"context switching\" refer to?", "Changing the desktop theme", "Saving and restoring the state of a CPU so multiple processes can share a single CPU", "Switching network protocols", "Rebooting the OS", "B",
     "Context switching stores the state of a currently running process and loads the state of another, enabling multitasking.", "Intermediate"),
    ("What is a semaphore used for in operating systems?", "Displaying error messages", "Controlling access to a shared resource by multiple processes/threads", "Formatting disks", "Managing user accounts", "B",
     "A semaphore is a synchronization tool that controls access to shared resources using counters and wait/signal operations.", "Intermediate"),
    ("What is thrashing in an operating system?", "Fast execution of processes", "Excessive paging activity that severely degrades system performance", "A type of virus", "A CPU scheduling algorithm", "B",
     "Thrashing occurs when the system spends more time swapping pages in/out of memory than executing actual processes.", "Advanced"),
    ("What is the main advantage of a multi-level feedback queue scheduling algorithm?", "It uses no memory", "It adapts process priority dynamically based on behavior and waiting time", "It only works for single-core CPUs", "It eliminates the need for context switching", "B",
     "Multi-level feedback queues adjust a process's priority/queue over time based on its CPU usage patterns, balancing responsiveness and fairness.", "Advanced"),
    ("What is the Banker's Algorithm used for?", "File compression", "Deadlock avoidance by simulating resource allocation before granting it", "Disk defragmentation", "Load balancing network traffic", "B",
     "The Banker's Algorithm checks whether granting a resource request keeps the system in a safe state, helping avoid deadlock.", "Advanced"),
    ("What is the difference between preemptive and non-preemptive scheduling?", "There is no difference", "Preemptive scheduling can interrupt a running process; non-preemptive cannot until it finishes or blocks", "Non-preemptive is always faster", "Preemptive only applies to I/O operations", "B",
     "Preemptive scheduling allows the OS to forcibly suspend a running process to allocate the CPU to another; non-preemptive scheduling waits for the process to voluntarily yield.", "Advanced"),
    ("What does a TLB (Translation Lookaside Buffer) do?", "Stores user passwords", "Caches recent virtual-to-physical address translations to speed up memory access", "Manages disk partitions", "Schedules I/O requests", "B",
     "A TLB is a hardware cache that stores recent page table translations, reducing the time needed for address translation.", "Advanced"),
]
