# Each question: (text, option_a, option_b, option_c, option_d, correct_letter, explanation, difficulty)

PYTHON_QUESTIONS = [
    ("Which keyword is used to define a function in Python?", "func", "def", "function", "lambda", "B",
     "The `def` keyword is used to declare a function in Python, e.g. `def greet():`.", "Beginner"),
    ("What is the output of `type([])` in Python?", "<class 'list'>", "<class 'array'>", "<class 'tuple'>", "<class 'dict'>", "A",
     "Square brackets `[]` create a list, so `type([])` returns `<class 'list'>`.", "Beginner"),
    ("Which of these is an immutable data type in Python?", "list", "dict", "tuple", "set", "C",
     "Tuples cannot be modified after creation, making them immutable, unlike lists, dicts, and sets.", "Beginner"),
    ("What does the `len()` function return for a string?", "The memory size", "The number of characters", "The ASCII value", "The number of words", "B",
     "`len()` returns the number of characters (elements) in a string.", "Beginner"),
    ("How do you start a single-line comment in Python?", "//", "#", "/*", "--", "B",
     "Python uses the `#` symbol to begin a single-line comment.", "Beginner"),
    ("What is the correct file extension for Python files?", ".pt", ".pyt", ".py", ".python", "C",
     "Python source files use the `.py` extension.", "Beginner"),
    ("Which operator is used for floor division in Python?", "/", "//", "%", "**", "B",
     "The `//` operator performs floor division, discarding the remainder (e.g. `7 // 2` is `3`).", "Beginner"),
    ("What will `print(3 == '3')` output?", "True", "False", "Error", "None", "B",
     "Python does not implicitly convert types when comparing, so an int and a str of the same value are not equal.", "Beginner"),
    ("Which method adds an item to the end of a Python list?", "add()", "append()", "insert()", "extend()", "B",
     "`append()` adds a single element to the end of a list.", "Beginner"),
    ("What is the output of `bool(0)`?", "True", "False", "0", "Error", "B",
     "In Python, `0` is falsy, so `bool(0)` evaluates to `False`.", "Beginner"),
    ("Which of the following creates a dictionary in Python?", "{1, 2, 3}", "[1, 2, 3]", "{'a': 1}", "(1, 2)", "C",
     "Curly braces with key-value pairs, like `{'a': 1}`, define a dictionary.", "Beginner"),
    ("What does the `range(5)` function generate?", "1 to 5", "0 to 4", "0 to 5", "1 to 4", "B",
     "`range(5)` generates numbers from 0 up to, but not including, 5.", "Beginner"),
    ("Which keyword is used to handle exceptions in Python?", "catch", "except", "handle", "rescue", "B",
     "Python uses `try`/`except` blocks to catch and handle exceptions.", "Intermediate"),
    ("What is a list comprehension used for?", "Sorting a list", "Creating a new list concisely", "Deleting a list", "Copying a dictionary", "B",
     "List comprehensions provide a concise syntax for creating lists, e.g. `[x*2 for x in range(5)]`.", "Intermediate"),
    ("What does `*args` allow a function to accept?", "A fixed number of arguments", "Keyword arguments only", "A variable number of positional arguments", "No arguments", "C",
     "`*args` collects any number of positional arguments into a tuple inside the function.", "Intermediate"),
    ("What is the purpose of the `self` parameter in a class method?", "It refers to the class itself", "It refers to the current instance of the class", "It is optional and unused", "It refers to the parent class", "B",
     "`self` refers to the specific instance calling the method, allowing access to its attributes.", "Intermediate"),
    ("Which module is commonly used for working with regular expressions in Python?", "regex", "re", "regexp", "pyregex", "B",
     "The built-in `re` module provides regular expression matching operations.", "Intermediate"),
    ("What does the `with` statement help manage in Python?", "Loops", "Resource cleanup (context managers)", "Exceptions only", "Variable scope", "B",
     "The `with` statement ensures resources like files are properly closed via context managers, even if an error occurs.", "Intermediate"),
    ("What is the output of `[1, 2, 3] + [4, 5]` in Python?", "[1, 2, 3, 4, 5]", "[5, 7, 8]", "Error", "[1, 2, 3, [4, 5]]", "A",
     "The `+` operator concatenates two lists into one.", "Intermediate"),
    ("What does `__init__` represent in a Python class?", "A destructor method", "The constructor method", "A static method", "An abstract method", "B",
     "`__init__` is the constructor, automatically called when a new instance of the class is created.", "Intermediate"),
    ("What is a Python decorator primarily used for?", "Styling console output", "Modifying or extending a function's behavior without changing its code", "Declaring constants", "Importing modules", "C",
     "Decorators wrap a function to add extra functionality (like logging or timing) without altering the original function's source.", "Advanced"),
    ("What is the difference between `deepcopy` and `copy` in the `copy` module?", "There is no difference", "`deepcopy` copies nested objects recursively; `copy` only copies the top level", "`copy` is faster but unsafe", "`deepcopy` only works on strings", "B",
     "A shallow `copy` duplicates only the outer object, while `deepcopy` recursively duplicates all nested objects too.", "Advanced"),
    ("What does the Global Interpreter Lock (GIL) do in CPython?", "Prevents multiple threads from executing Python bytecode simultaneously", "Speeds up multi-threaded programs", "Manages memory allocation only", "Compiles Python to machine code", "A",
     "The GIL ensures only one thread executes Python bytecode at a time in CPython, which affects CPU-bound multithreading.", "Advanced"),
    ("What is a generator in Python?", "A function that returns a list", "A function that uses `yield` to produce values lazily", "A built-in class for random numbers", "A type of decorator", "B",
     "Generators use `yield` to produce a sequence of values one at a time, without storing them all in memory.", "Advanced"),
    ("What is the output of `id()` used for in Python?", "Returns the data type", "Returns the unique memory identity of an object", "Returns the length of an object", "Returns the hash value", "B",
     "`id()` returns a unique integer identifying an object's identity (typically its memory address in CPython).", "Advanced"),
]
