SQL_QUESTIONS = [
    ("What does SQL stand for?", "Structured Query Language", "Sequential Query Language", "Structured Question Language", "Simple Query Logic", "A",
     "SQL stands for Structured Query Language, used to manage and query relational databases.", "Beginner"),
    ("Which SQL statement is used to extract data from a database?", "GET", "SELECT", "EXTRACT", "OPEN", "B",
     "The `SELECT` statement retrieves data from one or more tables.", "Beginner"),
    ("Which clause is used to filter records in SQL?", "FILTER", "WHERE", "HAVING", "IF", "B",
     "The `WHERE` clause filters rows based on a specified condition before grouping.", "Beginner"),
    ("Which keyword is used to sort the result set in SQL?", "SORT BY", "ORDER BY", "GROUP BY", "ARRANGE BY", "B",
     "`ORDER BY` sorts the result set by one or more columns, ascending by default.", "Beginner"),
    ("Which SQL statement is used to add new data to a table?", "ADD", "INSERT INTO", "CREATE", "UPDATE", "B",
     "`INSERT INTO` adds new rows of data into a table.", "Beginner"),
    ("Which SQL keyword is used to remove duplicate rows from a result set?", "UNIQUE", "DISTINCT", "REMOVE", "FILTER", "B",
     "`SELECT DISTINCT` returns only unique rows, eliminating duplicates from the result.", "Beginner"),
    ("What does the `PRIMARY KEY` constraint ensure?", "The column can contain NULLs", "Uniquely identifies each row in a table", "The column stores text only", "The table has no duplicates anywhere", "B",
     "A `PRIMARY KEY` uniquely identifies each record in a table and cannot contain NULL values.", "Beginner"),
    ("Which JOIN returns only the matching rows from both tables?", "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL OUTER JOIN", "C",
     "`INNER JOIN` returns only rows that have matching values in both joined tables.", "Intermediate"),
    ("Which JOIN returns all rows from the left table and matched rows from the right table?", "INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "CROSS JOIN", "B",
     "`LEFT JOIN` returns all rows from the left table, with NULLs for unmatched rows in the right table.", "Intermediate"),
    ("What is the purpose of the `GROUP BY` clause?", "To sort results", "To group rows sharing a property so aggregate functions can be applied per group", "To filter rows before aggregation", "To join two tables", "B",
     "`GROUP BY` groups rows with the same values in specified columns, often paired with aggregate functions like COUNT or SUM.", "Intermediate"),
    ("What is the difference between `WHERE` and `HAVING`?", "They are identical", "`WHERE` filters rows before grouping; `HAVING` filters groups after aggregation", "`HAVING` filters rows before grouping", "`WHERE` only works with aggregate functions", "B",
     "`WHERE` filters individual rows before any grouping occurs, while `HAVING` filters aggregated groups afterward.", "Intermediate"),
    ("Which SQL command is used to modify existing records in a table?", "MODIFY", "UPDATE", "ALTER", "CHANGE", "B",
     "The `UPDATE` statement modifies existing rows in a table based on a condition.", "Beginner"),
    ("What does a `FOREIGN KEY` do?", "Encrypts a column", "Links a column to the primary key of another table to enforce referential integrity", "Speeds up all queries automatically", "Removes duplicate values", "B",
     "A `FOREIGN KEY` establishes a link between tables, ensuring the referenced value exists in the related table.", "Intermediate"),
    ("Which aggregate function returns the number of rows matching a condition?", "SUM()", "COUNT()", "TOTAL()", "ADD()", "B",
     "`COUNT()` returns the number of rows that match a specified condition or the total row count.", "Beginner"),
    ("What does the SQL `LIKE` operator do?", "Performs exact matches only", "Searches for a specified pattern in a column using wildcards", "Sorts data alphabetically", "Joins two tables", "B",
     "`LIKE` is used with wildcards (`%`, `_`) to search for a specified pattern within a column.", "Intermediate"),
    ("What is database normalization primarily used for?", "Making backups faster", "Reducing data redundancy and improving data integrity", "Encrypting sensitive data", "Increasing table size", "B",
     "Normalization organizes tables and relationships to minimize redundancy and dependency issues.", "Advanced"),
    ("What is a SQL transaction?", "A single SELECT query", "A sequence of operations executed as a single logical unit of work", "A type of index", "A stored view", "B",
     "A transaction groups multiple operations so they either all succeed (COMMIT) or all fail (ROLLBACK) together.", "Advanced"),
    ("What does the ACID acronym stand for in database transactions?", "Atomicity, Consistency, Isolation, Durability", "Access, Control, Identity, Data", "Aggregate, Compute, Insert, Delete", "Atomic, Cache, Index, Duplicate", "A",
     "ACID properties (Atomicity, Consistency, Isolation, Durability) guarantee reliable processing of database transactions.", "Advanced"),
    ("What is the purpose of a database index?", "To enforce foreign keys", "To speed up data retrieval at the cost of extra storage and slower writes", "To encrypt table data", "To automatically normalize tables", "B",
     "Indexes improve the speed of read/query operations by allowing faster lookups, though they add overhead to write operations.", "Advanced"),
    ("Which SQL clause limits the number of rows returned by a query?", "TOP ONLY", "LIMIT", "ROWCOUNT", "MAX", "B",
     "`LIMIT` (or `TOP`/`FETCH` in some dialects) restricts the number of rows returned by a query.", "Beginner"),
]
